### ISSUE TITLE
Issues with NextJS 15

### ISSUE THREAD

**Issue by leonardobetti** [ChangoMan/nextjs-typescript-mdx-blog#8]
hi all

I am working on setting up this template as my portfolio to showcase my work as a product designer. Although I am not a dev, I am attempting to update all the libraries with pnpm, and I’ve set Next.js to the latest version, along with adding Turbo to help improve site speed and page loading. However, I'm facing a deployment issue related to the file **app/posts/[slug]/page.tsx.** The build fails due to this type error:

```
Type error: Type '{ params: { slug: string; }; }' does not satisfy the constraint 'PageProps'.
Types of property 'params' are incompatible.
Type '{ slug: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
```

I’d appreciate any guidance on whether there’s an easy way to resolve this issue or if the template can be updated to align with the latest versions.

thank you in advance for your time and support

**Comment by Eddi3MS** [comment]
Hey there, looks like you're using next v15, params are now async, you need to wait for it like:

``` 
Promise<{ slug: string }>
```

[check this upgrade guide](https://nextjs.org/docs/app/building-your-application/upgrading/version-15#asynchronous-layout)

**Comment by leonardobetti** [comment]
thanks @Eddi3MS up and running now
